### ISSUE TITLE
App Login: Google/Facebook

### ISSUE THREAD

**Issue by artyymcflyy** [Codepath-Group11/MyMusic#3]
User coming to our app for the first needs to be able to login using google/facebook. The user object should be saved to Parse.

**Comment by kathyLA** [comment]
Having issue to configure google sign in ios sdk to working with parse server. (Able to get access token only with google sign in sdk)

temporary using the parse ios sdk built in class to connect user with facebook and twitter.
Will make an decision either switch to to the firebase or not really soon.
 
*ParseSignUp viewcontroller delegate can not be set. otherwise will causing fb or twitter oauth procress not showing up.

**Comment by kathyLA** [comment]
documentation can find on
https://github.com/Codepath-Group11/MyMusic/tree/login.
Didn't merge to the master yet
